# Generated by Django 5.1.5 on 2025-05-14 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='f_creac',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='boss',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materials',
            name='material_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobs',
            name='dmg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='crit_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='dmg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Administrador'), ('player', 'Jugador')], default='player', max_length=20),
        ),
    ]
