# Generated by Django 5.1.5 on 2025-05-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recu', '0002_boss_f_creac_boss_status_materials_material_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobs',
            name='dmg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recu.summoner'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recu.weapons'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='crit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='dmg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
